/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthAction: typeof import('./src/components/public/auth-action/index.vue')['default']
    Avatar: typeof import('./src/components/public/avatar/index.vue')['default']
    Bg: typeof import('./src/components/public/layout-backgourd/components/bg.vue')['default']
    Count: typeof import('./src/components/count/index.vue')['default']
    DomLess: typeof import('./src/components/public/layout-backgourd/dom-less.vue')['default']
    DomMore: typeof import('./src/components/public/layout-backgourd/dom-more.vue')['default']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    ImgLazy: typeof import('./src/components/img-lazy/index.vue')['default']
    LangModal: typeof import('./src/components/public/lang-modal/index.vue')['default']
    Language: typeof import('./src/components/public/language/index.vue')['default']
    LayoutBackgourd: typeof import('./src/components/public/layout-backgourd/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrop: typeof import('naive-ui')['NDrop']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDropDown: typeof import('naive-ui')['NDropDown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PicItem: typeof import('./src/components/public/layout-backgourd/components/pic-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/skeleton/index.vue')['default']
    Time: typeof import('./src/components/time/index.vue')['default']
  }
}
